{% set name = "kedro" %}
{% set version = "0.19.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kedro-{{ version }}.tar.gz
  sha256: ae7a10410165911ad298f9267e866ec531de0a1b2dc4cb9274b46ca9119bcca2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - kedro = kedro.framework.cli:main
  number: 1
  script_env:
    - PYTHONWARNINGS="ignore::UserWarning"

requirements:
  host:
    - python >=3.8
    - setuptools >=65.5.1
    - pip
  run:
    - python >=3.8
    - attrs >=21.3
    - python-build >=0.7.0
    - cachetools >=4.1
    - click >=4.0
    - cookiecutter >=2.1.1,<3.0
    - dynaconf >=3.1.2,<4.0
    - fsspec >=2021.4
    - gitpython >=3.0
    - importlib-metadata >=3.6,<8.0
    - importlib-resources >=1.3,<7.0
    - jmespath >=0.9.5
    - kedro-datasets
    - more-itertools >=8.14.0
    - omegaconf >=2.1.1
    - parse >=1.19.0
    - pluggy >=1.0,<1.4.0
    - pre-commit-hooks
    - pyyaml >=4.2,<7.0
    - rich >=12.0,<14.0
    - rope >=0.21,<2.0
    - toml >=0.10.0
    - toposort >=1.5

test:
  imports:
    - kedro
  commands:
    - kedro --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kedro-org/kedro
  summary: A Python library that implements software engineering best-practice for data and ML pipelines.
  license: Apache-2.0
  license_file: LICENSE.md
  doc_url: https://kedro.readthedocs.io/
  dev_url: https://github.com/kedro-org/kedro
  description: A Python framework for creating reproducible, maintainable and modular data science code.

extra:
  recipe-maintainers:
    - marcelotrevisani
    - yetudada
    - idanov
    - merelcht
    - AhdraMeraliQB
    - NeroOkwa
    - noklam
    - SajidAlamQB
    - lrcouto
    - DimedS
