{% set name = "kedro" %}
{% set version = "0.18.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quantumblacklabs/kedro/archive/{{ version }}.tar.gz
  sha256: c03a58747e2fda1ad551c6e771dc8ed04678d6bb569b6da41f25babc4cf0fec2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - kedro = kedro.framework.cli:main

requirements:
  host:
    - pip
    - python >=3.7,<3.11
  run:
    - anyconfig >=0.10.0,<0.11.0
    - attrs >=21.3,<22.0
    - cachetools >=4.1,<5.0
    - click <9.0
    - cookiecutter >=2.1.1,<3.0
    - dynaconf >=3.1.2, <4.0
    - fsspec >=2021.4,<=2022.7.1
    - gitpython >=3.0,<4.0
    - importlib_metadata >=3.6
    - importlib_resources >=1.3
    - jmespath >=0.9.5,<1.0
    - jupyter_client >=5.1,<7.0
    - pip-tools >=6.10,<7.0
    - pluggy >=1.0,<1.1
    - python >=3.7,<3.11
    - python-json-logger >=2.0.0,<3.0.0
    - pyyaml >=4.2,<7.0
    - rich >=12.0,<13.0
    - rope >=1.5.1,<1.6
    - setuptools >=65.5.1
    - toml >=0.10,<0.11
    - toposort >=1.5,<2.0

test:
  imports:
    - kedro
  commands:
    - kedro --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantumblacklabs/kedro
  summary: A Python library that implements software engineering best-practice for data and ML pipelines.
  license: Apache-2.0
  license_file: LICENSE.md
  doc_url: https://kedro.readthedocs.io/
  dev_url: https://github.com/quantumblacklabs/kedro
  description: A Python framework for creating reproducible, maintainable and modular data science code.

extra:
  recipe-maintainers:
    - marcelotrevisani
    - yetudada
    - idanov
    - merelcht
    - AntonyMilneQB
    - AhdraMeraliQB
    - jmholzer
    - NeroOkwa
    - noklam
    - SajidAlamQB
